### FEATURE ENGINEERING
### IMBALANCED DATASET 
### PERFORMING Up Scaling AND DOWN Scaling

In [3]:
import numpy as np
import pandas as pd

np.random.seed(123)

n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

In [4]:
n_class_0,n_class_1

(900, 100)

In [5]:
class_0 = pd.DataFrame({
    'feature1': np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature2': np.random.normal(loc=0, scale=1, size=n_class_0),
    'target': [0]*n_class_0
})
class_1 = pd.DataFrame({
    'feature1': np.random.normal(loc=2, scale=1, size=n_class_1),
    'feature2': np.random.normal(loc=2, scale=1, size=n_class_1),
    'target': [1]*n_class_1
})

In [6]:
df = pd.concat([class_0,class_1]).reset_index(drop=True)

In [8]:
df.head()
df.tail()

     feature1  feature2  target
995  1.376371  2.845701       1
996  2.239810  0.880077       1
997  1.131760  1.640703       1
998  2.902006  0.390305       1
999  2.697490  2.013570       1

In [9]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

### UP SCALING

In [10]:
df_minor = df[df['target']==1]
df_major = df[df['target']==0]

In [17]:
from sklearn.utils import resample
df_minor_upsampled = resample(df_minor, replace=True, # sample with replacement
         n_samples = len(df_major),
         random_state = 42
         )

In [20]:
df_minor_upsampled.head()

     feature1  feature2  target
951  1.125854  1.843917       1
992  2.196570  1.397425       1
914  1.932170  2.998053       1
971  2.272825  3.034197       1
960  2.870056  1.550485       1

In [24]:
df_upsampled = pd.concat([df_major,df_minor_upsampled])
df_upsampled['target'].value_counts()

target
0    900
1    900
Name: count, dtype: int64

### DOWN SCALING

In [25]:
df_minor = df[df['target']==1]
df_major = df[df['target']==0]
from sklearn.utils import resample
df_major_downsampled = resample(df_major, replace=False, # sample with replacement
         n_samples = len(df_minor),
         random_state = 42
         )
df_major_downsampled.shape

(100, 3)

In [27]:
df_downsampled = pd.concat([df_minor, df_major_downsampled])
df_downsampled

     feature1  feature2  target
900  1.699768  2.139033       1
901  1.367739  2.025577       1
902  1.795683  1.803557       1
903  2.213696  3.312255       1
904  3.033878  3.187417       1
..        ...       ...     ...
398 -0.168426  0.553775       0
76  -0.403366  0.081491       0
196 -0.269293  0.611238       0
631 -0.295829  0.671673       0
751 -0.553404  0.804438       0

[200 rows x 3 columns]

In [28]:
df_downsampled['target'].value_counts()

target
1    100
0    100
Name: count, dtype: int64