# Nominal Encoding or One Hat encoding 
refers to converting categorical data values into numerical values by representing each category using binary vector

In [2]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [3]:
df = pd.DataFrame({
    'color':['red','green','blue','green','red','blue']
})

In [4]:
df

   color
0    red
1  green
2   blue
3  green
4    red
5   blue

In [5]:
encoder = OneHotEncoder()

In [7]:
# perform fit and then transform
encoded = encoder.fit_transform(df[['color']]).toarray()

In [8]:
encoder_df = pd.DataFrame(encoded,columns = encoder.get_feature_names_out())

In [9]:
encoder_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         0.0          1.0        0.0
2         1.0          0.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0